# Generated by Django 2.1.1 on 2018-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date-published')),
            ],
        ),
    ]
