# Generated by Django 2.1.1 on 2018-09-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0002_auto_20180928_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='pub_date',
        ),
    ]
