# Generated by Django 2.1.4 on 2019-01-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0003_remove_registration_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
            ],
        ),
    ]
